### PR TITLE
Additional ToT Kernels

### PR DESCRIPTION
**Pull request by ryanmrichard**
As far as I can tell `einsum` only supports multiplying ToTs with other ToTs. I need TA to be able to evaluate expressions like:

```.cpp
C("i,k;m,n") = A("i,j") * B("j,k;m,n");
C("i,k;m,n") = A("i,j") * B("k,j;m,n");
C("i,k;m,n") = A("j,m") * B("i,k;j,n");
C("i,k;m,n") = A("j,m") * B("i,k;n,j");
```
Right now all I have done is add unit tests for the desired operations (the code does not compile). If someone else thinks they can implement them in the near future that would be great; otherwise I'll poke around and see what I can do using what's in `einsum` already as a template.

### CODE REVIEW

**Comment by ryanmrichard** [comment]
> @evaleev unless I'm missing something there may be a problem. Right now I form an AO to PNO transformation like:
> 
> ```c++
> C_ao2pno("i,j;m,A") = C_ao2pao("m,a") *C_pao2pno("i,j;a,A");
> ```
> 
> Assuming the ToTs have to be `DistArray<TileType<TileType<T>>, PolicyType>` rather than something like `DistArray<DistArray<TileType<T>, PolicyType>>` this requires `C_ao2pao` to be a single tile. The latter would allow us to distribute `C_ao2pao` and the contraction works as long as that distribution is compatible with the inner distribution of `C_pao2pno`.
> 
> For the record, in the DLPNO code I currently replicate `C_ao2pao` for each `ij` getting a quantity `C_ao2pao("i,j;mu,a")` that way I have a ToT times a ToT (which is currently supported). I discovered this issue while working on this PR.
> 
> Admittedly to get quantities in the PNO basis set I probably don't have to go from the AO basis set. Nevertheless going from PAO to PNO doesn't solve the problem because, as the DLPNO code stands, PAO quantities are in normal tensors too. For example to compute the PNO overlaps I'd still have to do something like:
> 
> ```c++
> S_pno("i,j,k;A,B") = C_pao2pno("i,j;a,A") * S("a,b") *C_pao2pno("k,j;b,B");
> ```
> 
> which still involves the same sort of contraction (tensor with inner tensor of a ToT).

@evaleev have you had a chance to think about this?

**Comment by evaleev** [comment]
@ryanmrichard `C_ao2pno("i,j;m,A") = C_ao2pao("m,a") * C_pao2pno("i,j;a,A")` does not make sense. The ToT representation does not allow to express the idea that the inner mode `a` in `C_pao2pno("i,j;a,A")` for the given outer index tuple `{i,j}` is a subset of index range representing mode `a` in `C_ao2pao("m,a")`. E.g. when you construct `C_ao2pao` did you never encoded mapping of inner modes to other modes.

`C_ao2pno("i,j;m,A") = C_ao2pao("i,j;mu,a") * C_pao2pno("i,j;a,A")` involves `C_ao2pao("i,j;mu,a")` which is in essense encodes the mapping of mode `a` in `C_pao2pno("i,j;a,A")` onto mode `a` in `C_ao2pao("m,a")` *and* encodes the the mapping of mode `m` in `C_ao2pno("i,j;m,A")` onto mode `m` in `C_ao2pao("m,a")`. But these mappings are now external to the definitions of `C_pao2pno` and `C_ao2pno`. I'm not sure whether encoding these mappings in `C_pao2pno` and `C_ao2pno` makes sense though. Ultimately TA algebra will always imply metadata definitions that are external to the TA (e.g.  `TA::Range`s do not have semantic identity ... e.g. notion of AO and MO is external to TA).

**Comment by evaleev** [comment]
I think the proper solution is to implement `C_ao2pao("i,j;mu,a")` and `S_pao("i,j;a,b")` as lazily-evaluated tensors if want to avoid storing them. This type of extraction of subblocks (sieving) is in practice exactly what your manually-written code would have to do anyway.

**Comment by evaleev** [comment]
@ryanmrichard probably best to do this offline. too much typing. There are multiple ways to use ToT but some are more natural than others. `C_ao2pao("i,j;m,a")` is better than `C_ao2pao("i;j,m,a")` because mode `j` is not PNO-like (unitarily rotated in a manner dependent on `i`) ... for a given `i` the sequence of relevant `j` is non-contiguous. But inner modes in ToT are contiguous. So to represent such mode as an inner mode of ToT would mean you need extra metadata to interpret the contents of such tile. This violated the key design trait of TA, that every tile is contains all of its metadata (there is a reason TA::Tensor's range must support nonzero offsets so that its reader can understand where it fits in the TiledRange; this is unlike the "naive" designs like numpy, Eigen::Tensor, etc.). To represent `i->j` sparsity the traditional TA means (TiledRange+SparseShape) are enough, so making them both outer modes works and also avoid artificial asymmetry in their relationship (`j->i` is as valid as `i->j` ... the choice of one vs the other is algorithm, rather than data structure, specific).

**Comment by ryanmrichard** [comment]
Thanks for the response. I think I see what you're after. I've been working on other things since my last post, and am not in the same mindset anymore though. I'm hoping to get back to the DLPNO code by next week at the latest. Once I've had a chance to reacquaint myself, I'll see if this solves my problem or not.

**Comment by ryanmrichard** [comment]
I'm going to close this PR. The operations I was trying to implement are outside the scope of ToTs and after working with @evaleev offline I don't think I need them for the DLPNO code anymore either.

**Pull request closed without merging**
