### PR TITLE
evaluate “conversion” ops in Expr as tasks

### PR DESCRIPTION
**Pull request by evaleev**

### CODE REVIEW

**Comment by justusc** [comment]
Why make this change? Eval_tile is already a run as a task. All you have done is make a task that spawns a task and likely increased the evaluation time of those tiles.

**Comment by evaleev** [comment]
Push to master is accident due to awkward pullreq mechanism in sourcetree.

This will turn into support for nonblocking conversions. Probably best to
be done by finishing mixed expressions branch but I am not sure how baked
that code is

**Comment by justusc** [comment]
The task structure was fine for tile type conversions. Any type conversion was already done inside tasks in a non-blocking fashion. I designed it with lazy tiles in mind, which is also a type of tile conversion. The return type might need to be altered for tile type conversion.

What about the code do you see as blocking?

**Comment by evaleev** [comment]
the conversion operators all return values rather than futures. this assumes that the conversion can proceed fully without blocking. we want to be able to have user tiles that can only be converted to future<eval_type> rather than eval_type.

**Comment by justusc** [comment]
I think I see the direction you are going here. You want to move the responsibility of scheduling work for tile conversion out of the expression code an into some external (possibly user defined) function. Is that correct?

A few scenarios where this could be useful:
- Tile data is composed of more than one source, which may or may not be the result of other tasks.
- Data is located on a remote machine

This is essentially the problem I had in SUMMA.

Two recommendations:
1. Consider using my parallel reduce algorithm (see https://github.com/ValeevGroup/tiledarray/blob/master/src/TiledArray/reduce_task.h)
2. Move task generation out of the expression assignment completely. Any tasks generated there are almost certainly going to yield no-op tasks.

**Comment by evaleev** [comment]
yes, you understand correctly. we already are using the parallel reduction, and that's what produces the future<eval_type>. I think the current structure of how expressions are processed is very powerful and the nonblocking conversion can fit into it naturally. it's just a matter of updating all spots where tile conversion occurs. It may warrant switch to c++14 to make it more readable (e.g. LazyTile's `operator eval_type` will become `operator auto` to autodeduce the return type of op, etc.).

**Comment by justusc** [comment]
There are several places where tiles are evaluated:
- each distributed evaluator has the capability of evaluating input tiles,
- expression assignment functions
- block expression assignment functions

It might be a good idea to abstract out that capability since it is used in so many places.

**Comment by evaleev** [comment]
That's why I was looking at mixed expressions branch since that had
customizable cast ...

**Pull request merged**
