### PR TITLE
Enable Tensor of Tensor: Transposes

### PR DESCRIPTION
**Pull request by ryanmrichard**
Depends on #196. My goal for the moment is to accomplish the most fundamental expressions I can
think of, transposes. Depending on how much code that amounts to I may expand the scope of this PR.

```c++
DistArray<Tensor<Tensor<double>>> a, b;
a("i,j;a,b") = b("i,j;a,b);
a("j,i;a,b") = b("i,j;a,b);
a("i,j;b,a") = b("i,j;a,b");
a("j,i;b,a") = b("i,j;a,b");
// a("i,a;j,b") = b("i,j;a,b") is an error
```
This PR:
- [x] refactors `Tensor::trace` into a free function
- [x] tweaks the logic of `DistArray::operator()` to support indices of ToTs
- [x] adds unit tests for `DistArray::operator()`

TODO:
- [x] unit test new trace code
- [x] transpose

### CODE REVIEW

**Comment by ryanmrichard** [comment]
This PR is r2g with the caveat that I need a bit of help from @evaleev to get the BTAS inner tensors to work. If you pull this PR and uncomment lines 48 to 50 of `tests/tot_array_fixture.h` and try to compile `src/TiledArray/expressions/expr.h` line 439 will lead to an error (the actual error occurs in `tensor_interface.h` when it attempts to permute the BTAS range). Being blunt I'm not sure what non-invasive call to use to resolve the problem as I don't understand how all the non-invasive APIs fit together (there's the tile interface, the tensor interface, the Permute class, and a permute free-function all of which seem to have an overload for permuting the BTAS tensor). Having multiple ways to do the same thing makes it really hard to debug ADL problems.

**Comment by evaleev** [comment]
@ryanmrichard `btas::Range` is not usable with `TA::Range`. Please use `TA::Range` as the range parameter in defining the `btas::Tensor` usable (wrapped in `TA::Tile`) as a tile in `TA::DistArray`

**Comment by ryanmrichard** [comment]
@evaleev I thought I followed you, but that still doesn't seem to work. I checked in what I tried, [this](https://github.com/ValeevGroup/tiledarray/blob/c97240ca2758e2b85ce85929bce0fd9324d1ff50/src/TiledArray/expressions/expr.h#L440) is the relevant line.

**Comment by ryanmrichard** [comment]
Included in #218

**Pull request closed without merging**
