### PR TITLE
Added deep copies to sparse shape, one modifies the norms the other d…

### PR DESCRIPTION
**Pull request by calewis**
…oesn't

### CODE REVIEW

**Comment by justusc** [comment]
I have two issues:

1. The mutating clone operation is not a clone. The function name should reflect its purpose.
2. The tensor clone and mutate operation, `op(tile_norms_.clone())`, is very inefficient. The `op` should be given the original via a const reference, and create a modified copy. If the user wants to implement bad code, that is fine. But it should not be baked into TA.

**Comment by justusc** [comment]
That looks better. Can you add a unit test for the function? 

With that last change and a passing travis-ci test I will call it good.

**Comment by calewis** [comment]
@justusc I think everything is ready.  I now have the function update the zero_tile_count and added a unit test.

**Comment by justusc** [comment]
@calewis The changes you made to transform look good. I see making the unit test helped you find an error.

One possible improvement to this function would be to change the expected interface such that the output is a tensor of norms and the zero tile count. The advantage of this approach would be that it could avoid iterating over the tensor data twice. The disadvantage is that it creates an opportunity for users to introduce errors or abuse the interface.

I think your implementation is the safer, but less optimal, way to go.  What do you think?

**Comment by calewis** [comment]
@justusc I agree, that it is less optimal, but I think it is asking a lot of users to worry about zero_tile_count, also if we tell users it is their job to provide correct norms, are they suppose to normalize them or not? 

The way it is written does the correct thing in the following case. 
````c++
auto op = [](Tensor<float> const &t){
      return t;
};

auto shape = other_shape.transform(op);
````

I think the identity operation really should be this simple, so I don't like making users update zero_tile_count also if our user implements something like 

````c++
op = [](Tensor<float> const &t){
    Tensor<float> new = t.clone();
    for(auto i = 0; i < new.range().volume(); ++i){
         new[i] -= 0.01;
    }
    return new;
}
````
should they really need to check every new value against the threshold?

**Comment by evaleev** [comment]
I think transform is a reasonable interface. If someone wants every bit of performance they are expected to be capable of grabbing the norms and applying tform to them directly.

**Comment by justusc** [comment]
@evaleev That is a good point.

**Comment by calewis** [comment]
@evaleev, what you are suggesting isn't actually possible, incidentally this is why I made transform.  There is no easy non-const way to access the norm tensor of the shape and there is also no deep copy at the moment.

**Comment by justusc** [comment]
@calewis is correct. I forgot that the constructors always normalize and count zero tiles. The constructor used by transform is a private constructor.

**Comment by evaleev** [comment]
No reason for SparseShape not to provide at least the norm tensor. And perhaps expose the low-level ctor.

**Comment by justusc** [comment]
@evaleev The tensor is accessible via `SparseShape::data()`. The private constructor is for internal construction of new shapes, where there is no need to do error checking, count zero tiles, initialize the trange data, or normalize the tensor data. If we exposed this constructor, then it creates confusion for the users since the input data must be in a different format than the other constructors.

Transform already adds the potential for more confusion than I would like since it exposes the internal representation to the user. Though I think it is a reasonable compromise to the alternative, which requires a lot of potentially unnecessary work.

@calewis I guess the question I should have asked earlier is... What is your use for this function? Are you using it to filter certain tiles to be zero, or will you use it do more complex computation?

Most of the shape computation that has been done so far has been used to feed set_shape expressions, which could be solved with simple predicates.

**Comment by calewis** [comment]
@justusc  My current use case is I need to call set_shape on an expression, but the shape I want to use to set depends in some form on a currently existing shape. In my specially case if a row in a specific flattening of the norm tensors is zero then I want my output shape to be zero, but if any element in the row is not zero I want every element to be not zero.

**Comment by calewis** [comment]
@justusc The tensor is not accessible in the way Edward means (SparseShape::data()) because there is no non-const function so the following isn't possible. 

````c++
auto new_shape = shape.clone();
new_shape.data[0] = 100.0;
````

**Comment by justusc** [comment]
@calewis I expected it was something like that. Do you think you could form a predicate for your specific use case that does not require you to construct a new shape?

I am not sure @evaleev meant ...
```
auto new_shape = shape.clone();
new_shape.data()[0] = 100.0; 
```

My current feeling about expression set_shape is that it is forcing users to create copies of shapes, which are very data heavy. Maybe it is worth while going back and modifying the set_shape function to take a predicate? Though I am not sure that this is the correct approach either as it may not be applicable to shapes other than SparseShape.

**Comment by calewis** [comment]
@justusc without non-const access there is no hackn-slash fast way to copy and modify a shape. I suppose I could use a predicate, but it would need to hold a reference to an already existing shape. 

I know you are very concerned with performance, but I think ease of use is important and set_shape with a new shape is easy. We could provide a shape_predicate function also, but I think the existing interface is useful.

**Comment by justusc** [comment]
@calewis I think it would be reasonable for a predicate to use an existing shape as a basis for a predicate, as long as it does not involve a deep copy. Another option would be to compute and store a small amount of data. In the case you describe, maybe a vector of flags that indicate if a row or column is all zero. 

I know it may not always seem like I am concerned with easy of use, but it is a top priority in addition to performance. The problem is that the two are often in conflict. Ideally, I try to create an interface that is easy to use *and* by design has good performances characteristics.

I absolutely want to avoid an interface that encourages users to implement poor code, or code in TA that imposes poor performance in a user's application (unless there is no option). In the case of set_shape expressions, I think we have both.

**Comment by calewis** [comment]
Let's return to the topic.  Regardless of intended use SparseShape does not have any options for having non-normalized norms (aside from unnecessarily complicated construction), if not transform, then there needs to be a non-normalizing constructor or non-const data access. 

Transform is really about providing at least one interface to have a SparseShape where the values in the norm tensor are actually set by the user. It's an option that needs to exist.

**Comment by justusc** [comment]
@calewis Agreed.

**Comment by justusc** [comment]
Well I intended to merge and close this pull request, but it looks like I just closed the issue. I will fix that shortly. Sorry about that.

**Pull request merged**
