### PR TITLE
systematic replacement of deprecated functions

### PR DESCRIPTION
**Pull request by evaleev**
(intended to make method names consistent across the class hierarchy):

- get_world() -> world()
- get_shape() -> shape()
- get_pmap() -> pmap()
- tiles() -> tile_range()
- elements() -> element_range()
- make_tile_range(i) -> tile(i)

### CODE REVIEW

**Comment by evaleev** [comment]
to be followed up by the corresponding wiki updates

**Comment by justusc** [comment]
Overall good changes. However, I gave `make_tile_range()` and `make_range()` functions a different name since they are not simple accessors like the other functions. The make_* functions construct a new object and allocate memory. I think it is an important distinction to make with the name of the function. Otherwise, users are tempted to write code like:
```
auto lobound = trange.tile(i).lobound();
auto unbound = trange.tile(i).upbound();
auto extent = trange.tile(i).extents();
auto volume = trange.tile(i).volume();
...
```
which will allocate memory 4 times and result in a non-obvious data access errors. By prepending the functions with `make_`, it explicitly tells the user that the function constructs a new object.

**Comment by evaleev** [comment]
good point about make_X vs X. I'm not sure if we should worry about this (although I like it). If we revert to make_tile_range, there will be 2 functions with similar sounding names that can lead to confusion ...  make_tile_range (make a range for 1 tile) and tile_range (make a range of tile indices for the TiledRange).

This also solves only a piece of the big problem, that the user has to read docs to reason about operation complexity. I'm not sure if names alone solve the issue.

any suggestions how to rename element_range, tile_range, and tile(idx) such that the names (1) communicate the semantics clearly, and (2) are distinct enough please let me know.

**Comment by evaleev** [comment]
bump @justusc

**Comment by justusc** [comment]
I think the original names for the `TiledRange::tiles` and `TiledRange::elements` are the best I can think of. The are more consistent with the`DistArray` pmap, world, and shape naming conventions, which I like. However, I think your suggestions are reasonable. 

m

**Comment by evaleev** [comment]
OK, I will rename element_range -> elements_range, tile_range -> tiles_range, tile(i) -> make_tile_range(i)

**Pull request merged**
