### PR TITLE
Fixed an error in SparseShape::block_range

### PR DESCRIPTION
**Pull request by justusc**
Fixed an error whereSparseShape::block_range incorrectly modified the bock size when constructing size vectors for a new SparseShape object. This should fix the error in Issue #81.

### CODE REVIEW

**Comment by justusc** [comment]
CI seems to be broken due to missing llvm packages.

**Comment by evaleev** [comment]
ported CI fixes from master ... fingers xed

**Comment by evaleev** [comment]
@calewis please check compile error https://travis-ci.org/ValeevGroup/tiledarray/jobs/139307139#L8618

**Comment by justusc** [comment]
I committed a change that should fix the constructor problem in ValArray.

**Comment by justusc** [comment]
I think we should not be running CI tests with multiple MPI processes. If I remember correctly, I did not include that test because I was getting errors on the CI platform that I could not reproduce OS X or Linux platforms.

**Comment by evaleev** [comment]
Bumped Travis-CI to re-build PR; now that master builds OK this PR should too

**Pull request merged**
